### ISSUE TITLE
请问一下这个“cType ”如何使用

### ISSUE THREAD

**Issue by seasonl2014** [lqsong/admin-element-vue#1]
// 如果设置了cType 说明是自定义 添加 Content-Type类型 为自定义post 做铺垫
        if (config['cType']) {
            config.headers['Content-Type'] = 'application/x-www-form-urlencoded;charset=UTF-8';
        }

**Comment by lqsong** [comment]
[request.ts](https://github.com/lqsong/admin-element-vue/blob/typescript.v2/src/utils/request.ts) 基于 `axios` 封装， `axios`  的 `Content-Type` 头, 默认是 `application/json; charset=utf-8` 类型，在一些特殊情况下比如表单上传等需要 `application/x-www-form-urlencoded;charset=UTF-8` 类型时，有以下方法：

一、自己自定义headers：

```typescript
import request from '@/utils/request';

request({
      url: '/upload',
      method: 'post',
      headers: {
          'Content-Type':  'application/x-www-form-urlencoded;charset=UTF-8'
      }
  });
```

二、自定义[request.ts](https://github.com/lqsong/admin-element-vue/blob/typescript.v2/src/utils/request.ts) 工具为了使用方便，自己封装了一个cType类型
```typescript
import request from '@/utils/request';

request({
      url: '/upload',
      method: 'post',
      cType: true
  });
```

**Comment by seasonl2014** [comment]
> [request.ts](https://github.com/lqsong/admin-element-vue/blob/typescript.v2/src/utils/request.ts) 基于 `axios` 封装， `axios` 的 `Content-Type` 头, 默认是 `application/json; charset=utf-8` 类型，在一些特殊情况下比如表单上传等需要 `application/x-www-form-urlencoded;charset=UTF-8` 类型时，有以下方法：
> 
> 一、自己自定义headers：
> 
> ```ts
> import request from '@/utils/request';
> 
> request({
>       url: '/upload',
>       method: 'post',
>       headers: {
>           'Content-Type':  'application/x-www-form-urlencoded;charset=UTF-8'
>       }
>   });
> ```
> 
> 二、自定义[request.ts](https://github.com/lqsong/admin-element-vue/blob/typescript.v2/src/utils/request.ts) 工具为了使用方便，自己封装了一个cType类型
> 
> ```ts
> import request from '@/utils/request';
> 
> request({
>       url: '/upload',
>       method: 'post',
>       cType: true
>   });
> ```

明白了，非常感谢
