### ISSUE TITLE
关于 el-dialog 双向绑定父组件的visible的写法优化

### ISSUE THREAD

**Issue by Luckyman98** [lqsong/admin-element-vue#11]
el-dialog使用props.visible有更简便的使用，使用@close = "$emit('update:visible',false)" 直接可以关闭弹窗，在父组件中需要将visible改为v-model双向绑定形式，您现在的写法类似于React单向数据流的思想。只是个人觉得可以优化的点，谢谢。

**Comment by lqsong** [comment]
> el-dialog使用props.visible有更简便的使用，使用@close = "$emit('update:visible',false)" 直接可以关闭弹窗，在父组件中需要将visible改为v-model双向绑定形式，您现在的写法类似于React单向数据流的思想。只是个人觉得可以优化的点，谢谢。

你指的是哪个分支那个快代码
