### ISSUE TITLE
去除国际化

### ISSUE THREAD

**Issue by Drswith** [lqsong/admin-element-vue#13]
因为业务需要，不需要国际化插件。。有没有办法简单点删除的。。

**Comment by lqsong** [comment]
> 因为业务需要，不需要国际化插件。。有没有办法简单点删除的。。

直接删掉右上角选择国际化组件。

然后开发的时候有两种方法：

一种：
直接写中文

另一种：
只创建zh-cn.ts在里面写中文，页面调用，此方法后期方便扩展。
