### ISSUE TITLE
为什么我的组件属性类型转换识别不到

### ISSUE THREAD

**Issue by ChartWay** [lqsong/admin-element-vue#14]
![image](https://user-images.githubusercontent.com/44427400/147310683-cba7b3d6-53d7-49ed-876a-888f60853fb1.png)

图中的values设置了 Object as PropType<Partial<TableListItem>>,但是values的类型还是unknown，是需要引入什么插件吗？还是有其他什么要求？

**Comment by lqsong** [comment]
> 图中的values设置了 Object as PropType<Partial>,但是values的类型还是unknown，是需要引入什么插件吗？还是有其他什么要求？

你鼠标放到props上面看下他的values类型
