### ISSUE TITLE
request中的封装是否有问题？

### ISSUE THREAD

**Issue by yang-jh971** [lqsong/admin-element-vue#18]
经过测试，当用户token过期后，通过编译进入系统，初次会报错401，而当报此错时，service.interceptors.response.use（）执行的是error回调

**Comment by lqsong** [comment]
> 经过测试，当用户token过期后，通过编译进入系统，初次会报错401，而当报此错时，service.interceptors.response.use（）执行的是error回调

哪个分子？请提供在线代码

**Comment by yang-jh971** [comment]
import store from '@/store';
import axios from 'axios';
import {
  Message,
  MessageBox
} from 'element-ui';
import {
  serverLoginUrl,
  ajaxResponseNoVerifyUrl
} from '@/settings'; //ajaxHeadersTokenKey
import {
  isExternal
} from '@/utlis/validate';
import CONFIG_INFO from '../../config';

// 创建一个axios实例
const service = axios.create({
  baseURL: CONFIG_INFO.BASE_URL,
  withCredentials: false, // 当跨域请求时发送cookie  可解决跨域
  timeout: 10 * 1000 // 请求超时时间  0 不做限制
});

console.log("1111111111111111111111111111111111111");

// 全局设置 - post请求头
// service.defaults.headers.post['Content-Type'] = 'application/x-www-form-urlencoded;charset=UTF-8';

// POST 方法封装  (文件上传)
export const uploadFileRequest = (url, params) => {
  return axios({
    method: 'post',
    url: url,
    data: params,
    headers: {
      'Content-Type': 'multipart/form-data'
    }
  });
};

//  GET 方法封装
export const getRequest = (url) => {
  console.log("url", url);
  return axios({
    method: 'get',
    url: url
  });
};

//  PUT 方法封装
export const putRequest = (url, params) => {
  return axios({
    method: 'put',
    url: url,
    data: params,
    transformRequest: [function (data) {
      let ret = '';
      for (let it in data) {
        ret += encodeURIComponent(it) + '=' + encodeURIComponent(data[it]) + '&';
      }
      return ret;
    }],
    headers: {
      'Content-Type': 'application/x-www-form-urlencoded'
    }
  });
};

//  DELETE 方法封装
export const deleteRequest = (url) => {
  return axios({
    method: 'delete',
    url: url
  });
};

// 请求拦截器 - 在发送请求之前
service.interceptors.request.use(
  config => {
    console.log("请求拦截",store.getters.token);
    // 每个api都会将token带在url后
    if (store.getters.token) {
      //   // store.getters.token 加载时已在 [store/user] 用 getToken()获取Token
      //   // 让每个请求携带令牌
      //   // ajaxHeadersTokenKey -> ['X-Token'] 是自定义头key
      //   config.headers[ajaxHeadersTokenKey] = store.getters.token;
        config.params.token = store.getters.token;
      }
      // 如果设置了cType 说明是自定义 添加 Content-Type类型 为自定义post 做铺垫
      if (config.cType) {
        config.headers['Content-Type'] = 'application/x-www-form-urlencoded;charset=UTF-8';
      }
      console.log("configconfig", config);
      return config;
    },
    error => {
      // 处理请求错误
      console.log(error); // for debug
      return Promise.reject(error);
    }
);

// 响应拦截器
service.interceptors.response.use(
  response => {
    const res = response.data;
    const code = response.status; //HTTP状态码
    console.log("response", response);
    console.log("状态码", code, typeof code);
    console.log("对比", 200, typeof 200);
    console.log(code !== 200);
    // 如果自定义代码不是200，则判断为错误。
    if (code !== 200) {
      // 获取替换后的字符串
      const reqUrl = response.config.url.split("?")[0].replace(response.config.baseURL, '');
      const noVerifyBool = ajaxResponseNoVerifyUrl.includes(reqUrl);

      switch (code) {
        case 401: // 未登陆
          if (!noVerifyBool) {
            MessageBox({
              title: '提示',
              showClose: false,
              closeOnClickModal: false,
              closeOnPressEscape: false,
              message: '当前用户登入信息已失效，请重新登入再操作',
              beforeClose: (action, instance, done) => {
                if (isExternal(serverLoginUrl)) {
                  window.location.href = serverLoginUrl;
                } else {
                  window.location.reload();
                }
                console.log(action, instance, done);
              }
            });
          }
          break;

        default:
          if (!noVerifyBool) {
            Message({
              message: res.msg || 'Error',
              type: 'error',
              duration: 2 * 1000
            });
          }
          break;
      }
      // 返回错误 走 catch 
      return Promise.reject(res);
    } else {
      // 返回体的errCode不为0，表示请求有误，此处只做弹窗处理，具体交由页面去做
      if (res.errCode && res.errCode !== 0) {
        Message({
          message: res.errStr,
          type: 'error',
          duration: 2 * 1000
        });

      }
      return res;
    }
  },
  error => {
    console.log('requestJS中的err' + error); // for debug
    Message({
      message: error.message,
      type: 'error',
      duration: 2 * 1000
    });
    return Promise.reject(error);
  }
);

export default service;

**Comment by lqsong** [comment]
> 经过测试，当用户token过期后，通过编译进入系统，初次会报错401，而当报此错时，service.interceptors.response.use（）执行的是error回调

过期了就是未登录啊？这个逻辑没有问题啊？

**Comment by lqsong** [comment]
> 经过测试，当用户token过期后，通过编译进入系统，初次会报错401，而当报此错时，service.interceptors.response.use（）执行的是error回调

code代码是后端返回的，这个要看你和后端的定义，你自己可以改的，你定义400001都没人管，看自己和后端的沟通

**Comment by yang-jh971** [comment]
> > 经过测试，当用户token过期后，通过编译进入系统，初次会报错401，而当报此错时，service.interceptors.response.use（）执行的是error回调
> 
> code代码是后端返回的，这个要看你和后端的定义，你自己可以改的，你定义400001都没人管，看自己和后端的沟通

**Comment by yang-jh971** [comment]
不是HTTP状态码的问题，是响应拦截器直接进入了error报错，并没有进入response进行判断。而且我看浏览器也没有发出过请求

**Comment by lqsong** [comment]
> 不是HTTP状态码的问题，是响应拦截器直接进入了error报错，并没有进入response进行判断。而且我看浏览器也没有发出过请求

那是因为开发的时候启用了mock，默认启用了本地mock，所以你看不到http请求

**Comment by yang-jh971** [comment]
我改了  我这里已经没mock了

**Comment by lqsong** [comment]
> 我改了 我这里已经没mock了

那就不清楚，你是怎么改的了 ^^

**Comment by yang-jh971** [comment]
你好，我知道了，你在响应拦截中的response中，根本拦截不到4**、5**之类的这种错误代码。只能在error那里拦截的到。
