### ISSUE TITLE
这个项目做的非常好，希望作者多封装几个常用组件

### ISSUE THREAD

**Issue by seasonl2014** [lqsong/admin-element-vue#2]
比如：树形穿梭框、树形下拉框、省市县三级联动等

**Comment by lqsong** [comment]
> 比如：树形穿梭框、树形下拉框、省市县三级联动等

感谢您的宝贵建议，你说的 `element` 都是有的，比如：

[https://element-plus.org/#/zh-CN/component/cascader](https://element-plus.org/#/zh-CN/component/cascader)
[https://element-plus.org/#/zh-CN/component/transfer](https://element-plus.org/#/zh-CN/component/transfer)

所以不知道，您这边指的是哪方面。
