### ISSUE TITLE
Cannot find namespace '__WebpackModuleApi' from my vscode

### ISSUE THREAD

**Issue by sdeass** [lqsong/admin-element-vue#5]
where can be found '__WebpackModuleApi' which is file of store?

export function importAllStore<S> (): ModuleTree<S> {
    const modules: ModuleTree<S> = {};
    try {
        // 导入 @/views 下文件，包含子目录，文件名为：store.ts
        const viewsRequireContext: __WebpackModuleApi.RequireContext = require.context('../views', true, /[/\\]store\.ts$/); 
        viewsRequireContext.keys().forEach(fileName => {
            // 获取内容
            const modulesConent = viewsRequireContext(fileName);
            if(modulesConent.default) {
              const { name, ...module } = modulesConent.default; 
              // 获取 PascalCase 命名
              const modulesName = name || fileName.replace(/^\.\/(.*)\.\w+$/, "$1");
            
              modules[modulesName] = { ...module }; 
            }

        });  
        
        // 导入 @/store 下文件 
        const requireContext: __WebpackModuleApi.RequireContext = require.context('../store', false, /\.ts$/);    
        requireContext.keys().forEach(fileName => {
          // 获取内容
          const modulesConent = requireContext(fileName);
          if(modulesConent.default) {
              const { name, ...module } = modulesConent.default; 
              // 获取 PascalCase 命名
              const modulesName = name || fileName.replace(/^\.\/(.*)\.\w+$/, "$1");
            
              modules[modulesName] = { ...module }; 
          }
          
        });
    } catch (error) {
      // eslint-disable-next-line no-console
      console.log(error);
    }

    return modules;
}

**Comment by lqsong** [comment]
What are the detailed errors？

**Comment by lqsong** [comment]
QQ已沟通，自己修改框架架构问题。
