### ISSUE TITLE
请教一下关于CKEditor上传图片的问题

### ISSUE THREAD

**Issue by seasonl2014** [lqsong/admin-element-vue#8]
使用CKEditor上传图片后，如何修改图片的尺寸大小和给图片添加一个链接地址呢？

**Comment by lqsong** [comment]
为了防止项目过大，本项目只是简单集成了`CKEditor`,你说的功能需要`CKEditor`安装 `@ckeditor/ckeditor5-image`和`@ckeditor/ckeditor5-link` 插件。
请参考官方文档：[https://ckeditor.com/docs/ckeditor5/latest/features/image.html#installation](https://ckeditor.com/docs/ckeditor5/latest/features/image.html#installation)
