### ISSUE TITLE
请问下.env.development 的参数

### ISSUE THREAD

**Issue by robber2000** [lqsong/admin-element-vue#9]
请问下.env.development 的参数是怎么读取进去的，再那个步骤，还是说webpack 就会会这样读取

**Comment by lqsong** [comment]
`vue-cli`集成的，请查看官方文档[https://cli.vuejs.org/zh/guide/mode-and-env.html#环境变量](https://cli.vuejs.org/zh/guide/mode-and-env.html#环境变量)、与源代码[https://github.com/vuejs/vue-cli/blob/dev/packages/%40vue/cli-service/lib/Service.js#L93](https://github.com/vuejs/vue-cli/blob/dev/packages/%40vue/cli-service/lib/Service.js#L93)
